
eureka:
  client:
    serviceUrl:
      defaultZone: http://106.12.124.234:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${random.value}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json

